In [1]:
# dataset  loader 
from sklearn.datasets import make_classification
import torch

In [2]:
X , y = make_classification(n_samples= 1000 , n_features=2 , n_informative=2 , n_redundant=0 ,n_classes = 2 , random_state = 0)


In [3]:
X

array([[-1.44101238e+00, -7.80766668e-01],
       [ 1.60532092e-03,  1.41689818e+00],
       [-9.63649472e-01,  1.03086158e+00],
       ...,
       [-6.53088749e-02, -1.03761973e+00],
       [-4.80992293e-01,  2.58989027e-01],
       [-4.95123673e-02, -1.87640163e+00]], shape=(1000, 2))

In [4]:
y

array([0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,

In [5]:
# Convert the data to PyTorch tensors
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

In [6]:
from torch.utils.data import Dataset, DataLoader

In [23]:
class CustomDataset(Dataset):

  def __init__(self, features, labels):

    self.features = features
    self.labels = labels

  def __len__(self):

    return self.features.shape[0]

  def __getitem__(self, index):

    return self.features[index], self.labels[index]
        

In [24]:
dataset = CustomDataset(X , y)


In [25]:
len(dataset)


1000

In [26]:
dataset[2]

(tensor([-0.9636,  1.0309]), tensor(1))

In [27]:
dataset[0 : 10]

(tensor([[-1.4410e+00, -7.8077e-01],
         [ 1.6053e-03,  1.4169e+00],
         [-9.6365e-01,  1.0309e+00],
         [-2.2987e+00,  2.3814e+00],
         [-3.0089e-01,  7.4481e-01],
         [-8.6914e-01,  1.2240e+00],
         [-2.0905e+00, -1.2981e+00],
         [ 3.7704e-01,  8.3093e-01],
         [-1.6042e+00, -3.0944e-01],
         [-1.6083e+00, -8.3841e-01]]),
 tensor([0, 1, 1, 1, 1, 1, 0, 1, 1, 0]))

In [17]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=False)

In [ ]:
for batch_features , batch_lables in dataloader : 
    print(batch_features)
    print(batch_lables)
    print("-" * 50)

tensor([[-1.4410, -0.7808],
        [ 0.0016,  1.4169]])
tensor([0, 1])
--------------------------------------------------
tensor([[-0.9636,  1.0309],
        [-2.2987,  2.3814]])
tensor([1, 1])
--------------------------------------------------
tensor([[-0.3009,  0.7448],
        [-0.8691,  1.2240]])
tensor([1, 1])
--------------------------------------------------
tensor([[-2.0905, -1.2981],
        [ 0.3770,  0.8309]])
tensor([0, 1])
--------------------------------------------------
tensor([[-1.6042, -0.3094],
        [-1.6083, -0.8384]])
tensor([1, 0])
--------------------------------------------------
tensor([[1.0650, 0.9094],
        [2.0249, 0.8331]])
tensor([1, 1])
--------------------------------------------------
tensor([[-1.5147,  1.3568],
        [-0.7256, -2.5492]])
tensor([1, 0])
--------------------------------------------------
tensor([[ 0.9894, -1.5152],
        [-1.6889, -1.0967]])
tensor([0, 0])
--------------------------------------------------
tensor([[ 0.7543,  0