In [ ]:
import torch 
device=  "cuda" if torch.cuda.is_available() else "cpu"
a = torch.tensor([1,2,3,4])
a.to(device)

tensor([1, 2, 3, 4], device='cuda:0')

In [5]:
import time 
size = 1000 
matrix_cpu1 = torch.rand(size , size)
matrix_cpu2 = torch.rand(size , size )

start_time = time.time()
matrix_cpu1 = torch.matmul(matrix_cpu1 ,matrix_cpu2)

end_time = time.time()

print(f"Time taken for CPU: {end_time - start_time} seconds")

Time taken for CPU: 0.05607771873474121 seconds


In [6]:
matrix_gpu1 = matrix_cpu1.to(device)
matrix_gpu2 = matrix_cpu2.to(device)

start_time = time.time()
matrix_gpu1 = torch.matmul(matrix_gpu1 ,matrix_gpu2)
end_time = time.time()

print(f"Time taken for GPU: {end_time - start_time} seconds")


Time taken for GPU: 0.12044644355773926 seconds


In [15]:
import numpy as np


a= torch.tensor([1,2,3,4])

a.flatten()
b = a.numpy()


print(b)


c=  np.array([1,2,3,4])

d= torch.tensor(c)
d = torch.from_numpy(c)

print(d)
d

[1 2 3 4]
tensor([1, 2, 3, 4])


tensor([1, 2, 3, 4])

In [17]:
# learnin about the auto grad 
y = X**2


def dy_dx(X):
    return 2*X

X = torch.tensor([1.0, 2.0, 3.0])

dy_dx(X)


tensor([2., 4., 6.])

In [ ]:
X = torch.tensor(3.0 , requires_grad= True)

y = X**2

y.backward()

print(X.grad)

# THIS IS THE AUTOMATIC DERIVATIVE OF THE FUNCTION Y = X^2 AT X = 3.0 WHICH IS 2*X = 6.0


tensor(6.)


In [22]:
from math import sin

x = torch.tensor(1.0 , requires_grad= True)

y = x**2 
z = torch.sin(y)

z.backward()

print(x.grad)
print(x.grad == 2*x*torch.cos(x**2)
      )

tensor(1.0806)
tensor(True)


In [29]:
import torch

# Inputs
x = torch.tensor(6.7)  # Input feature
y = torch.tensor(0.0)  # True label (binary)

w = torch.tensor(1.0)  # Weight
b = torch.tensor(0.0)  # Bias




In [30]:
# Binary Cross-Entropy Loss for scalar
def binary_cross_entropy_loss(prediction, target):
    epsilon = 1e-8  # To prevent log(0)
    prediction = torch.clamp(prediction, epsilon, 1 - epsilon)
    return -(target * torch.log(prediction) + (1 - target) * torch.log(1 - prediction))

In [ ]:
# forward pass 
z = w * x + b
y = torch.sigmoid(z)

loss = binary_cross_entropy_loss(y_pred , y_true)




NameError: name 'y_' is not defined

In [33]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import warnings 
warnings.filterwarnings("ignore")


In [35]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification
from sklearn.preprocessing import LabelEncoder



In [38]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [45]:
X = df.drop(columns=['diagnosis'])
y = df['diagnosis']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [47]:
scaler = StandardScaler()
encoder = LabelEncoder()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

y_train_enc= encoder.fit_transform(y_train)
y_test_enc = encoder.transform(y_test)




In [57]:
X_train_scaled_tensor = torch.from_numpy(X_train_scaled)
X_test_scaled_tensor = torch.from_numpy(X_test_scaled)


In [59]:
y_train_enc_tensor = torch.from_numpy(y_train_enc)
y_test_enc_tensor = torch.from_numpy(y_test_enc)


In [67]:
learning_rate= 0.01 
epochs = 25



In [74]:
from numpy import dtype


class MySimpleNN():

    def __init__(self , X):
        
        self.weights = torch.rand(X.shape[1] , 1 , requires_grad=True , dtype = torch.float64)
        self.bias = torch.rand(1 , dtype = torch.float64 , requires_grad=True)

    def forward(self , X):
        z = torch.matmul(X , self.weights) + self.bias
        y_pred = torch.sigmoid(z)

        return y_pred

    def loss(self , y_pred , y):
        # clamp prediction to avoid log(0) error 
        epsilon = 1e-8
        y_pred = torch.clamp(y_pred , epsilon , 1-epsilon)

        loss = -(y * torch.log(y_pred) + (1-y) * torch.log(1-y_pred))
        loss = loss.mean() #  i dont know why are we doing this but i wil find out 
        return loss 
    
    
        

In [73]:
# create model
model = MySimpleNN(X_train_scaled_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_scaled_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_enc_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

TypeError: unsupported operand type(s) for *: 'numpy.ndarray' and 'Tensor'